# Setup
title:               Unfortunately, posts
tagline:             I have no blog and I must post.
description:         "If you haven't heard me infodump before, this should be new."
url:                 https://posts.demarko.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dannel Jurado
  url:               https://demarko.org

social:
  name: Dannel Jurado
  links:
    - https://xoxo.zone/@demarko
    - https://bsky.app/profile/demarko.org
    - https://twitter.com/DeMarko/
    - https://github.com/DeMarko
    - https://www.kickstarter.com/profile/demarko

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  # - jekyll-og-image

# Custom vars
version:             0.5.1
google_analytics_id: #UA-XXXX-Y

defaults:
  - scope:
      path: ""
    values:
      image: https://demarko.org/assets/images/default_card.jpg

og_image:
  output_dir: "assets/images/og"
  image: "/assets/images/default_card.jpg"
  domain: "posts.demarko.org"
  border_bottom:
    width: 20
    fill:
      - "#017D5D"
      - "#00AE86"
      - "#EE6055"
      - "#FFD97D"